services:
  redis:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes --appendfsync everysec


  proxy:
    build:
      context: ./
      dockerfile: Containerfile
    depends_on:
      redis:
        condition: service_healthy
      kdf:
        condition: service_healthy
    environment:
      AUTH_APP_CONFIG_PATH: /usr/src/komodo-defi-proxy/assets/auth_conf.json
    volumes:
      - ./assets:/usr/src/komodo-defi-proxy/assets
      - ./public-key.pem:/usr/src/komodo-defi-proxy/public-key.pem:ro
      - ./private-key.pem:/usr/src/komodo-defi-proxy/private-key.pem:ro
    ports:
      - "127.0.0.1:6150:6150"
    restart: always

  kdf:
    build:
      context: ./kdf
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8967:8967" # RPC
      - "127.0.0.1:32326:32326" # TCP p2p
      - "127.0.0.1:32336:32336" # WSS p2p
    volumes:
      - ./kdf/DB:/root/.kdf/DB
      - ./kdf/MM2.json:/root/.kdf/MM2.json
      - ./kdf/coins:/root/.kdf/coins
      - ./kdf/healthcheck.sh:/root/healthcheck.sh
    healthcheck:
      test: ["CMD", "/bin/bash", "/root/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 30s
    restart: always

volumes:
  redis_data:
